# Generated by Django 5.2.5 on 2025-09-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teachar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
