# Generated by Django 5.2.5 on 2025-09-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0002_student_teachar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorandpatientdetails.teachar'),
        ),
    ]
