# Generated by Django 5.2.5 on 2025-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0003_student_teachar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hobby',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='habbice',
            field=models.ManyToManyField(to='doctorandpatientdetails.hobby'),
        ),
    ]
