# Generated by Django 5.2.5 on 2025-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0004_hobby_student_habbice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='habbice',
            field=models.ManyToManyField(related_name='students', to='doctorandpatientdetails.hobby'),
        ),
    ]
