# Generated by Django 5.2.5 on 2025-09-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0005_alter_student_habbice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachar',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='doctorandpatientdetails.teachar'),
            preserve_default=False,
        ),
    ]
