# Generated by Django 5.2.5 on 2025-09-19 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0006_alter_student_teachar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('is_activate', models.BooleanField(default=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='AdmittePatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activate', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorandpatientdetails.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorandpatientdetails.hospital')),
            ],
        ),
    ]
