# Generated by Django 5.2.5 on 2025-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorandpatientdetails', '0007_hospital_admittepatientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='habbice',
            field=models.ManyToManyField(to='doctorandpatientdetails.hobby'),
        ),
    ]
